### ISSUE TITLE
charPreset - unable to set custom chars

### ISSUE THREAD

**Issue by toltek7** [lemonce/svg-captcha#11]
**Which version of svg-captcha are you using?**
1.3.8
**Do you want to request a *feature* or report a *bug*?**
bug
**If this is a feature request, what is motivation for changing the behavior?**

**If it is a bug, which version of svg-captcha are you using?**
1.3.8
**What is the current behavior?**
Unable to set custom chars
**What is the expected behavior?**
Wnaht to set custom chars
**Step to reproduce the bug or other relevant information**
if you set to option charPreset, it will not work. The problem in random.js file line 32 (let chars = opts.charPreset;) please change this line to let chars = options.charPreset || opts.charPreset;

**Comment by steambap** [comment]
As you can see in README.md, there is no `charPreset` option for `create` API. It is only avaible for global options API `svgCaptcha.options.charPreset`. I thought nobody will want to set character preset for every call to `create` API.

Anyway, it is nice to let people have this option.

And since you already point out how to fix it, do you think you can make a PR?

**Comment by toltek7** [comment]
Got it. Sure, i can do it, please provide an access to the repository, will create a branch with this fix

**Comment by steambap** [comment]
It's fixed in 1.3.9.

Here is a guide on how to fork a project and make a pull request: https://guides.github.com/activities/forking/
And here is a practice repo: https://github.com/octocat/Spoon-Knife
If you know how to fix things, you can make a pull request without access to the repo.

**Comment by toltek7** [comment]
Thanks steambap!
