### ISSUE TITLE
More secure way to transform letters

### ISSUE THREAD

**Issue by stck** [lemonce/svg-captcha#3]
Hello, it seems that transform by matrix is not secure, because skew removes when we remove attribute. So my proposal is to transform letters not on "render" stage of browser, but before we transform letters into path. How do you think about that?

**Comment by steambap** [comment]
I made the mistake of using matrix transformation before. It's removed in later version. I use a 3d-ish font to make up for that. It's in the new version (1.1.0).  
  
That said, I had some search done when I was using matrix transform.  
To transform a path, you need some linear algebra and it is slow, which is no good for a synchronized api. I guess that's why you need professional tool like Adobe illustrator or sketch to do vector graphics.

**Comment by stck** [comment]
@steambap Yes, it's seems like I was viewing outdated version.
